### ISSUE TITLE
Ssize_t problem

### ISSUE THREAD

**Issue by dirkson** [alestrooisma/ScrumbleDataFormat#1]
Heyo!

When compiling with warnings as errors, the following two lines produce an error about an implicit cast from ssize_t to int on my machine:

SdfParser.c:86
SdfParser.c:87

Casting the first argument to int suppresses the error on my machine.

Cheers,
-Dirk

**Comment by alestrooisma** [comment]
I cannot reproduce this error - what exact compiler options do you use?

**Comment by alestrooisma** [comment]
According to dirkson:
clang -O3 -fomit-frame-pointer -ffast-math -DHAVE_SSE2 -msse -msse2 -msse3 -mmmx -m3dnow -Werror  -Isupport/include/ -I/usr/local/include -DDSFMT_MEXP=521 -DGLEW_STATIC -c -o support/lib/lin/SdfParser.o support/libraries/SdfParser.c

**Comment by dirkson** [comment]
Using a freshly cloned copy of git, I was able to reproduce the problem with both of the following:
clang -Werror SdfParser.c
gcc -Werror SdfParser.c

clang 3.4, gcc 4.8. I also believe I've tried it on clang 3.5 to the same effect. OS's debian and ubuntu linux.

It's starting to be really strange that you have a problem reproducing. What OS?

Sorry I took so long in replying - You caught me in the middle of a day off.

Cheers,
-Dirk

**Comment by alestrooisma** [comment]
You are right, it was a mistake in the makefile: accidentally added the options to the linker call!
Anyway, it is fixed: the parser now compiles cleanly with -Werror -Wall -Wextra, which is the highest level of error coverage, I think.
