### ISSUE TITLE
getline restricts usage to posix

### ISSUE THREAD

**Issue by dirkson** [alestrooisma/ScrumbleDataFormat#2]
Heyo!

"getline()", is a glibc function. To allow compilation on windows, you'd either need to redefine it (There's a public domain copy here: http://stackoverflow.com/questions/735126/are-there-alternate-implementations-of-gnu-getline-interface ) or use something else.

Cheers,
-Dirk

**Comment by alestrooisma** [comment]
Fixed: now using fgets with self-written buffer enlargement.
